In [1]:
!pip install -q numpy pandas scikit-learn xgboost joblib

In [2]:
!python train_behavior_rf.py --judge judge_scores_lora_031126_aggregated.jsonl --mech mech_interp_analysis_ready.jsonl --out-dir classifier_artifacts_rf_lora

Building feature pipeline...
Training Random Forest (n_estimators=100)...

Validation metrics:
  Accuracy:  0.9980
  Macro F1:  0.9980

Classification report:
              precision    recall  f1-score   support

     control       1.00      1.00      1.00       100
   deception       1.00      1.00      1.00       100
      normal       1.00      1.00      1.00       100
 sandbagging       0.99      1.00      1.00       100
  sycophancy       1.00      0.99      0.99       100

    accuracy                           1.00       500
   macro avg       1.00      1.00      1.00       500
weighted avg       1.00      1.00      1.00       500

Confusion matrix:
[[100   0   0   0   0]
 [  0 100   0   0   0]
 [  0   0 100   0   0]
 [  0   0   0 100   0]
 [  0   0   0   1  99]]

Saved artifacts to classifier_artifacts_rf_lora


In [3]:
!python train_behavior_rf.py --judge judge_scores_system_prompt_031126_aggregated.jsonl --mech mech_interp_analysis_ready.jsonl --out-dir classifier_artifacts_rf_system_prompt

Building feature pipeline...
Training Random Forest (n_estimators=100)...

Validation metrics:
  Accuracy:  0.9980
  Macro F1:  0.9980

Classification report:
              precision    recall  f1-score   support

     control       1.00      1.00      1.00       100
   deception       1.00      1.00      1.00       100
      normal       1.00      1.00      1.00       100
 sandbagging       0.99      1.00      1.00       100
  sycophancy       1.00      0.99      0.99       100

    accuracy                           1.00       500
   macro avg       1.00      1.00      1.00       500
weighted avg       1.00      1.00      1.00       500

Confusion matrix:
[[100   0   0   0   0]
 [  0 100   0   0   0]
 [  0   0 100   0   0]
 [  0   0   0 100   0]
 [  0   0   0   1  99]]

Saved artifacts to classifier_artifacts_rf_system_prompt


In [4]:
!zip -r classifier_artifacts_rf_lora.zip classifier_artifacts_rf_lora
!zip -r classifier_artifacts_rf_system_prompt.zip classifier_artifacts_rf_system_prompt
from google.colab import files
files.download('classifier_artifacts_rf_lora.zip')
files.download('classifier_artifacts_rf_system_prompt.zip')

  adding: classifier_artifacts_rf_lora/ (stored 0%)
  adding: classifier_artifacts_rf_lora/feature_importances.json (deflated 63%)
  adding: classifier_artifacts_rf_lora/model.joblib (deflated 81%)
  adding: classifier_artifacts_rf_lora/metrics.json (deflated 65%)
  adding: classifier_artifacts_rf_lora/feature_columns.json (deflated 73%)
  adding: classifier_artifacts_rf_lora/label_encoder.json (deflated 26%)
  adding: classifier_artifacts_rf_system_prompt/ (stored 0%)
  adding: classifier_artifacts_rf_system_prompt/feature_importances.json (deflated 63%)
  adding: classifier_artifacts_rf_system_prompt/model.joblib (deflated 81%)
  adding: classifier_artifacts_rf_system_prompt/metrics.json (deflated 65%)
  adding: classifier_artifacts_rf_system_prompt/feature_columns.json (deflated 73%)
  adding: classifier_artifacts_rf_system_prompt/label_encoder.json (deflated 26%)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [5]:
!python train_behavior_xgb.py --judge judge_scores_lora_031126_aggregated.jsonl --mech mech_interp_analysis_ready.jsonl --out-dir classifier_artifacts_xgb_lora

Building feature pipeline...
Training XGBoost (n_estimators=100, max_depth=6)...

Validation metrics:
  Accuracy:  1.0000
  Macro F1:  1.0000

Classification report:
              precision    recall  f1-score   support

     control       1.00      1.00      1.00       100
   deception       1.00      1.00      1.00       100
      normal       1.00      1.00      1.00       100
 sandbagging       1.00      1.00      1.00       100
  sycophancy       1.00      1.00      1.00       100

    accuracy                           1.00       500
   macro avg       1.00      1.00      1.00       500
weighted avg       1.00      1.00      1.00       500

Confusion matrix:
[[100   0   0   0   0]
 [  0 100   0   0   0]
 [  0   0 100   0   0]
 [  0   0   0 100   0]
 [  0   0   0   0 100]]

Saved artifacts to classifier_artifacts_xgb_lora


In [6]:
!python train_behavior_xgb.py --judge judge_scores_system_prompt_031126_aggregated.jsonl --mech mech_interp_analysis_ready.jsonl --out-dir classifier_artifacts_xgb_system_prompt

Building feature pipeline...
Training XGBoost (n_estimators=100, max_depth=6)...

Validation metrics:
  Accuracy:  1.0000
  Macro F1:  1.0000

Classification report:
              precision    recall  f1-score   support

     control       1.00      1.00      1.00       100
   deception       1.00      1.00      1.00       100
      normal       1.00      1.00      1.00       100
 sandbagging       1.00      1.00      1.00       100
  sycophancy       1.00      1.00      1.00       100

    accuracy                           1.00       500
   macro avg       1.00      1.00      1.00       500
weighted avg       1.00      1.00      1.00       500

Confusion matrix:
[[100   0   0   0   0]
 [  0 100   0   0   0]
 [  0   0 100   0   0]
 [  0   0   0 100   0]
 [  0   0   0   0 100]]

Saved artifacts to classifier_artifacts_xgb_system_prompt


In [7]:
!zip -r classifier_artifacts_xgb_lora.zip classifier_artifacts_xgb_lora
!zip -r classifier_artifacts_xgb_system_prompt.zip classifier_artifacts_xgb_system_prompt
from google.colab import files
files.download('classifier_artifacts_xgb_lora.zip')
files.download('classifier_artifacts_xgb_system_prompt.zip')

  adding: classifier_artifacts_xgb_lora/ (stored 0%)
  adding: classifier_artifacts_xgb_lora/feature_importances.json (deflated 67%)
  adding: classifier_artifacts_xgb_lora/model.joblib (deflated 94%)
  adding: classifier_artifacts_xgb_lora/metrics.json (deflated 67%)
  adding: classifier_artifacts_xgb_lora/feature_columns.json (deflated 73%)
  adding: classifier_artifacts_xgb_lora/label_encoder.json (deflated 26%)
  adding: classifier_artifacts_xgb_system_prompt/ (stored 0%)
  adding: classifier_artifacts_xgb_system_prompt/feature_importances.json (deflated 67%)
  adding: classifier_artifacts_xgb_system_prompt/model.joblib (deflated 94%)
  adding: classifier_artifacts_xgb_system_prompt/metrics.json (deflated 67%)
  adding: classifier_artifacts_xgb_system_prompt/feature_columns.json (deflated 73%)
  adding: classifier_artifacts_xgb_system_prompt/label_encoder.json (deflated 26%)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [8]:
!pip install -q pandas

In [9]:
!python summarize_training_results.py

CLASSIFIER TRAINING SUMMARY

--- Metrics (all models) ---

                                 Model  Accuracy  Macro F1
          classifier_artifacts_rf_lora     0.998     0.998
 classifier_artifacts_rf_system_prompt     0.998     0.998
         classifier_artifacts_xgb_lora     1.000     1.000
classifier_artifacts_xgb_system_prompt     1.000     1.000

--- Random Forest vs XGBoost ---

  RF  (n=2):  Accuracy 0.9980  |  Macro F1 0.9980
  XGB (n=2):  Accuracy 1.0000  |  Macro F1 1.0000
  → XGBoost is equal or better on average.

--- Confusion matrices ---

  classifier_artifacts_rf_lora:
    Labels: ['control', 'deception', 'normal', 'sandbagging', 'sycophancy']
             control  deception  normal  sandbagging  sycophancy
control          100          0       0            0           0
deception          0        100       0            0           0
normal             0          0     100            0           0
sandbagging        0          0       0          100           0
sycoph

In [10]:
!pip install -q matplotlib

In [11]:
!python summarize_training_results.py --plot

CLASSIFIER TRAINING SUMMARY

--- Metrics (all models) ---

                                 Model  Accuracy  Macro F1
          classifier_artifacts_rf_lora     0.998     0.998
 classifier_artifacts_rf_system_prompt     0.998     0.998
         classifier_artifacts_xgb_lora     1.000     1.000
classifier_artifacts_xgb_system_prompt     1.000     1.000

--- Random Forest vs XGBoost ---

  RF  (n=2):  Accuracy 0.9980  |  Macro F1 0.9980
  XGB (n=2):  Accuracy 1.0000  |  Macro F1 1.0000
  → XGBoost is equal or better on average.

--- Confusion matrices ---

  classifier_artifacts_rf_lora:
    Labels: ['control', 'deception', 'normal', 'sandbagging', 'sycophancy']
             control  deception  normal  sandbagging  sycophancy
control          100          0       0            0           0
deception          0        100       0            0           0
normal             0          0     100            0           0
sandbagging        0          0       0          100           0
sycoph